# Generated by Django 5.0 on 2023-12-27 16:59

import monostat.opsgenie.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpsgenieConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        default=monostat.opsgenie.models.generate_secret,
                        max_length=255,
                        verbose_name="Webhook secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpsGenie Configuration",
            },
        ),
    ]
