# Generated by Django 5.0 on 2023-12-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "planned"),
                            ("suspected", "suspected"),
                            ("dismissed", "dismissed"),
                            ("confirmed", "confirmed"),
                            ("watching", "watching"),
                            ("resolved", "resolved"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("notice", "Notice"),
                            ("bug", "Known Bug"),
                            ("partial", "Partial Outage"),
                            ("outage", "Full Outage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("title", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="pretix", max_length=255, verbose_name="System name"
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@pretix.eu",
                        max_length=254,
                        verbose_name="Support email",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        default="+49 6221 3217750",
                        max_length=50,
                        verbose_name="Support phone",
                    ),
                ),
                (
                    "legal_url",
                    models.URLField(
                        default="https://pretix.eu/about/en/imprint",
                        verbose_name="Legal notice URL",
                    ),
                ),
                (
                    "privacy_url",
                    models.URLField(
                        default="https://pretix.eu/about/en/privacy",
                        verbose_name="Privacy policy URL",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B1C4A", max_length=50, verbose_name="Primary color"
                    ),
                ),
                (
                    "link_color",
                    models.CharField(
                        default="#7F4A91", max_length=50, verbose_name="Link color"
                    ),
                ),
                (
                    "success_color",
                    models.CharField(
                        default="#50A167", max_length=50, verbose_name="Success color"
                    ),
                ),
                (
                    "warning_color",
                    models.CharField(
                        default="#FFB419", max_length=50, verbose_name="Warning color"
                    ),
                ),
                (
                    "danger_color",
                    models.CharField(
                        default="#C44F4F", max_length=50, verbose_name="Danger color"
                    ),
                ),
                (
                    "info_color",
                    models.CharField(
                        default="#5F9CD4", max_length=50, verbose_name="Info color"
                    ),
                ),
                (
                    "primary_text_color",
                    models.CharField(
                        default="#333333",
                        max_length=50,
                        verbose_name="Primary text color",
                    ),
                ),
                (
                    "secondary_text_color",
                    models.CharField(
                        default="#767676",
                        max_length=50,
                        verbose_name="Secondary text color",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="IncidentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planned", "planned"),
                            ("suspected", "suspected"),
                            ("dismissed", "dismissed"),
                            ("confirmed", "confirmed"),
                            ("watching", "watching"),
                            ("resolved", "resolved"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.incident"
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident update",
                "verbose_name_plural": "Incident updates",
            },
        ),
        migrations.CreateModel(
            name="IncomingAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("external_id", models.CharField(db_index=True, max_length=190)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.incident"
                    ),
                ),
            ],
            options={
                "verbose_name": "Incoming alert",
                "verbose_name_plural": "Incoming alerts",
            },
        ),
    ]
