# Generated by Django 5.0 on 2024-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_incident_options_alter_incidentupdate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="last_notified_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("planned", "planned"),
                    ("suspected", "suspected"),
                    ("dismissed", "dismissed"),
                    ("confirmed", "confirmed"),
                    ("watching", "watching"),
                    ("resolved", "resolved"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
