# Generated by Django 5.0 on 2024-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_incident_last_notified_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="silent",
            field=models.BooleanField(
                default=False, verbose_name="Never send notifications for this incident"
            ),
        ),
    ]
