# Generated by Django 5.0 on 2024-02-11 12:03

import monostat.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(max_length=254, verbose_name="Reply-to address"),
                ),
            ],
            options={
                "verbose_name": "Notification Configuration",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                ("active", models.BooleanField()),
                (
                    "token",
                    models.CharField(
                        default=monostat.notifications.models.generate_token,
                        max_length=255,
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
            },
        ),
    ]
