# Generated by Django 5.0 on 2024-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationconfiguration",
            name="allow_subscriptions",
            field=models.BooleanField(
                default=False, verbose_name="Allow new subscriptions"
            ),
        ),
    ]
