name: Build docker container
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t monostat .
    - name: Tag image
      run: docker tag monostat pretix/monostat:${GITHUB_REF##*/}
    - name: Docker push
      run: docker push pretix/monostat:${GITHUB_REF##*/}