# Generated by Django 5.0 on 2024-01-01 19:08

import monostat.slack.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        default=monostat.slack.models.generate_secret,
                        max_length=255,
                        verbose_name="Bot token",
                    ),
                ),
                (
                    "signing_secret",
                    models.CharField(
                        default=monostat.slack.models.generate_secret,
                        max_length=255,
                        verbose_name="Signing secret",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(max_length=255, verbose_name="Channel name"),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Channel name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Configuration",
            },
        ),
    ]
