# Generated by Django 5.0 on 2024-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackconfiguration",
            name="channel_id",
            field=models.CharField(
                blank=True,
                help_text="Will be filled automatically!",
                max_length=255,
                null=True,
                verbose_name="Channel ID",
            ),
        ),
    ]
